# Generated by Django 5.0.4 on 2024-04-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restauth", "0003_profile_image_path_meeting_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="users",
        ),
        migrations.AddField(
            model_name="profile",
            name="tags",
            field=models.ManyToManyField(to="restauth.tag"),
        ),
    ]
